server:
  port: 0

spring:
  application:
    name: ms-pagamentos
  datasource:
    url: jdbc:mysql://localhost/pagamentos?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password:
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
      properties: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ${USER_NAME}
    password: ${PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

resilience4j:
  circuitbreaker:
    instances:
      atualizarPedido:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s






logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
















